[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Secure 1inch Fusion Backend - READ-ONLY
# No private keys required - 1inch compliant
[environment]
NODE_ENV = "production" 